version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: people_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: people
    ports:
      - "5435:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
